# Generated by Django 4.2.16 on 2026-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('par_id', models.BigIntegerField(blank=True, null=True)),
                ('par_nom', models.CharField(blank=True, default='', max_length=150)),
                ('statut', models.CharField(choices=[('construit', 'Construit, non transféré'), ('publie', 'Publié'), ('echec', 'Échec')], max_length=20)),
                ('transfere', models.BooleanField(default=False)),
                ('taille', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('duree_s', models.FloatField(blank=True, null=True)),
                ('reponse_vps', models.TextField(blank=True, default='')),
                ('erreur', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'publication_journal',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRecue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recue_le', models.DateTimeField(db_index=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'publication_recue',
                'ordering': ['-recue_le'],
            },
        ),
    ]
