# Generated by Django 4.2.16 on 2026-10-11 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('texte', models.TextField()),
                ('cibles', models.JSONField(default=list)),
                ('resume', models.CharField(blank=True, default='', max_length=500)),
                ('nb_destinataires', models.PositiveIntegerField(default=0)),
                ('auteur_nom', models.CharField(blank=True, default='', max_length=150)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annonces_annonce',
                'ordering': ['-cree_le'],
            },
        ),
    ]
