# Generated by Django 4.2.16 on 2026-10-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_auditlog_core_audit__model_n_5ea3b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('BULK_CREATE', 'Création en masse'), ('BULK_UPDATE', 'Modification en masse'), ('BULK_DELETE', 'Suppression en masse'), ('ARCHIVE', 'Archivage'), ('RESTORE', 'Restauration'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('PASSWORD_RESET', 'Réinitialisation MDP'), ('PERMISSION_DENIED', 'Accès refusé'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('ACCOUNT_UNLOCKED', 'Compte débloqué')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlogarchive',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('BULK_CREATE', 'Création en masse'), ('BULK_UPDATE', 'Modification en masse'), ('BULK_DELETE', 'Suppression en masse'), ('ARCHIVE', 'Archivage'), ('RESTORE', 'Restauration'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('PASSWORD_RESET', 'Réinitialisation MDP'), ('PERMISSION_DENIED', 'Accès refusé'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('ACCOUNT_UNLOCKED', 'Compte débloqué')], max_length=20),
        ),
    ]
