# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suivi', '0001_initial'),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='departement.departement')),
            ],
            options={
                'db_table': 'absence_etudiant',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SeuilAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'absence_seuilabsence',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'Présent'), (1, 'Absent'), (2, 'Sanctionné'), (3, 'Justifiée')], default=0)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='absence.etudiant')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='suivi.suivie')),
            ],
            options={
                'db_table': 'absence_presence',
                'unique_together': {('suivi', 'etudiant')},
            },
        ),
    ]
