# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='adresse_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='cni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='scolarite.filiere'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite_ar',
            field=models.CharField(blank=True, default='موريتانية', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite_fr',
            field=models.CharField(blank=True, default='Mauritanienne', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='etudiants/photos/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé'), ('exclu', 'Exclu')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['statut'], name='absence_etu_statut_02d6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['filiere'], name='absence_etu_filiere_c7e3dc_idx'),
        ),
    ]
