# Generated by Django 6.0.3 on 2026-04-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_etudiant_adresse_ar_etudiant_adresse_fr_etudiant_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_bac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nbac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='serie_bac',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
