# Generated by Django 6.0.3 on 2026-04-18 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_add_bac_fields_to_etudiant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé'), ('exclu', 'Exclu'), ('transfere', 'Transféré')], default='actif', max_length=20),
        ),
    ]
