# Generated by Django 4.2.16 on 2026-06-10 15:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_etudiant_user_alter_etudiant_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/', validators=[core.validators.validate_document]),
        ),
    ]
