# Generated by Django 4.2.16 on 2026-06-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0006_alter_departement_decalage_impair_and_more'),
        ('absence', '0005_alter_presence_justificatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='departement.departement'),
        ),
    ]
