# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departement', '0001_initial'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_em', models.CharField(max_length=50)),
                ('intitule', models.CharField(max_length=200)),
                ('CM', models.IntegerField(default=0)),
                ('TD', models.IntegerField(default=0)),
                ('TP', models.IntegerField(default=0)),
                ('PR', models.IntegerField(default=0)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ems', to='departement.departement')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ems', to='parametres.semestre')),
            ],
            options={
                'db_table': 'em_em',
                'ordering': ['code_em'],
                'unique_together': {('code_em', 'departement')},
            },
        ),
    ]
