# Generated by Django 4.2.16 on 2026-04-13 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from core.migration_ops import DejaAppliqueeSurMySQL


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_initial'),
        ('em', '0001_initial'),
    ]

    operations = [
        # La table 'em' existe deja avec le bon nom en DB MySQL (0001 avait
        # 'em_em') — zero SQL. Sur base neuve non-MySQL : RENAME reel.
        DejaAppliqueeSurMySQL(
            state_operations=[
                migrations.AlterModelTable(name='em', table='em'),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='em',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='em',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='em',
            name='est_element_module',
            field=models.BooleanField(default=False, help_text='True si cet EM est un module LMD (conteneur) ou un élément de module (évaluable).'),
        ),
        migrations.AddField(
            model_name='em',
            name='module_parent',
            field=models.ForeignKey(blank=True, help_text='Module parent si cet EM est un élément de module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='em.em'),
        ),
        migrations.AddField(
            model_name='em',
            name='poids_cc',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='em',
            name='poids_exam',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='em',
            name='poids_tp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='em',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ems_responsable', to='prof.prof'),
        ),
        migrations.AddField(
            model_name='em',
            name='seuil_eliminatoire',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text="Note en dessous de laquelle l'UE est éliminatoire (ex : 6.00)", max_digits=4),
        ),
        # No-op : deja corrige au debut (rename table -> table = aucune SQL)
        DejaAppliqueeSurMySQL(
            state_operations=[migrations.AlterModelTable(name='em', table='em')],
            database_operations=[],
        ),
    ]
