# Generated by Django 4.2.16 on 2026-04-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0003_em_element_lmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='em',
            name='est_element_module',
        ),
        migrations.RemoveField(
            model_name='em',
            name='module_lmd',
        ),
        migrations.RemoveField(
            model_name='em',
            name='module_parent',
        ),
        migrations.RemoveField(
            model_name='em',
            name='poids_cc',
        ),
        migrations.RemoveField(
            model_name='em',
            name='poids_exam',
        ),
        migrations.RemoveField(
            model_name='em',
            name='poids_tp',
        ),
        migrations.RemoveField(
            model_name='em',
            name='responsable',
        ),
    ]
