# Generated by Django 6.0.3 on 2026-04-16 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0004_remove_em_est_element_module_remove_em_module_lmd_and_more'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='em',
            name='module_lmd',
            field=models.ForeignKey(blank=True, help_text='Module LMD auquel cet EM est rattaché (crédits, filière, semestre).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ems_planification', to='modules.module'),
        ),
    ]
