# Generated by Django 6.0.3 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0005_add_module_lmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='em',
            name='coefficient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
