# Generated by Django 4.2.16 on 2026-05-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_seed_special_seances'),
        ('em', '0008_em_departement_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='em',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ems', to='parametres.institution'),
        ),
    ]
