# Generated by Django 4.2.16 on 2026-06-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0012_alter_semestre_niveau_semestre'),
        ('em', '0010_em_institution_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='em',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ems', to='parametres.semestre'),
        ),
    ]
