# Generated by Django 4.2.16 on 2026-06-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0012_alter_semestre_niveau_semestre'),
        ('em', '0011_alter_em_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='em',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ems', to='parametres.semestre'),
        ),
    ]
