# Generated by Django 4.2.16 on 2026-07-22 12:41

from django.db import migrations, models
import django.db.models.deletion


def backfill_filiere(apps, schema_editor):
    """
    Renseigne EM.filiere AVANT l'ajout de la contrainte d'unicité (sinon les EM
    existants ne seraient pas protégés). Priorité à la chaîne stable :
      module_lmd.filiere  → sinon  departement.filiere  → sinon  NULL.
    NULL reste autorisé (Postgres : NULLs distincts → pas de dédup, aucun crash).
    """
    EM = apps.get_model('em', 'EM')
    for em in EM.objects.select_related('module_lmd', 'departement').all():
        fil_id = None
        if em.module_lmd_id and em.module_lmd and em.module_lmd.filiere_id:
            fil_id = em.module_lmd.filiere_id
        elif em.departement_id and em.departement and em.departement.filiere_id:
            fil_id = em.departement.filiere_id
        if fil_id and em.filiere_id != fil_id:
            em.filiere_id = fil_id
            em.save(update_fields=['filiere'])


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0009_parametresponderation_rattrapage_plafond_and_more'),
        ('em', '0012_alter_em_semestre'),
    ]

    operations = [
        # 1. Lever l'ancienne unicité (code_em, departement).
        migrations.AlterUniqueTogether(
            name='em',
            unique_together=set(),
        ),
        # 2. Ajouter la filière stable (nullable).
        migrations.AddField(
            model_name='em',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ems', to='scolarite.filiere'),
        ),
        # 3. Backfill AVANT la contrainte (protège les EM existants).
        migrations.RunPython(backfill_filiere, migrations.RunPython.noop),
        # 4. Nouvelle unicité (code_em, filiere).
        migrations.AddConstraint(
            model_name='em',
            constraint=models.UniqueConstraint(fields=('code_em', 'filiere'), name='uniq_em_code_em_filiere'),
        ),
    ]
