# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em', '0001_initial'),
        ('prof', '0001_initial'),
        ('salle', '0001_initial'),
        ('parametres', '0001_initial'),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prof', models.CharField(blank=True, max_length=50)),
                ('id_em', models.CharField(blank=True, max_length=50)),
                ('type_seance', models.CharField(blank=True, max_length=50)),
                ('jour', models.CharField(blank=True, max_length=20)),
                ('creneau', models.CharField(blank=True, max_length=100)),
                ('id_salle', models.CharField(blank=True, max_length=50)),
                ('id_departement', models.CharField(blank=True, max_length=200)),
                ('id_semestre', models.CharField(blank=True, max_length=50)),
                ('annee_universitaire', models.CharField(blank=True, max_length=20)),
                ('numero_semaine', models.IntegerField(default=0)),
                ('creneau_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.creneau')),
                ('departements', models.ManyToManyField(blank=True, related_name='pointages', to='departement.departement')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='em.em')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.prof')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salle.salle')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.semestre')),
            ],
            options={
                'db_table': 'suivi_suivie_pointage',
            },
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prof', models.CharField(blank=True, db_index=True, max_length=50)),
                ('id_em', models.CharField(blank=True, max_length=50)),
                ('type_seance', models.CharField(blank=True, max_length=50)),
                ('jour', models.CharField(blank=True, max_length=20)),
                ('creneau', models.CharField(blank=True, max_length=100)),
                ('id_salle', models.CharField(blank=True, max_length=50)),
                ('id_departement', models.CharField(blank=True, db_index=True, max_length=50)),
                ('id_semestre', models.CharField(blank=True, max_length=50)),
                ('annee_universitaire', models.CharField(blank=True, db_index=True, max_length=20)),
                ('numero_semaine', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_suivie', models.DateField(blank=True, null=True)),
                ('type_semestre', models.CharField(blank=True, max_length=1)),
                ('duree_creneau', models.FloatField(default=1.5)),
                ('taux_paiement', models.FloatField(default=0.0)),
                ('creneau_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivies', to='parametres.creneau')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivies', to='departement.departement')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivies', to='em.em')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivies', to='prof.prof')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivies', to='salle.salle')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivies', to='parametres.semestre')),
            ],
            options={
                'db_table': 'suivi_suivie',
                'ordering': ['-annee_universitaire', '-numero_semaine'],
            },
        ),
        migrations.CreateModel(
            name='ChargeInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_cm', models.IntegerField(default=0)),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='parametres.institution')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_institution', to='prof.prof')),
            ],
            options={
                'db_table': 'suivi_chargeinstitution',
                'unique_together': {('prof', 'institution', 'annee_universitaire')},
            },
        ),
    ]
