# Generated by Django 6.0.3 on 2026-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0005_create_chargeinstitution_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviepointage',
            name='reclamation_motif',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='suiviepointage',
            name='reclamation_statut',
            field=models.CharField(blank=True, choices=[('', 'Aucune'), ('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='', max_length=20),
        ),
    ]
