# Generated by Django 4.2.16 on 2026-05-30 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suivi', '0009_drop_legacy_charfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviGenerationAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('type_semestre', models.CharField(max_length=1)),
                ('numero_semaine', models.IntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suivi_auths_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suivi_generation_authorization',
                'indexes': [models.Index(fields=['user', 'annee_universitaire', 'type_semestre'], name='suivi_gener_user_id_b54c68_idx')],
                'unique_together': {('user', 'annee_universitaire', 'type_semestre', 'numero_semaine')},
            },
        ),
    ]
