# Generated by Django 4.2.16 on 2026-06-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_prof_actif_alter_prof_banque'),
        ('suivi', '0010_add_generation_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeinstitution',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_institution', to='prof.prof'),
        ),
    ]
