# Generated by Django 4.2.16 on 2026-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0011_alter_chargeinstitution_prof'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suiviepointage',
            index=models.Index(fields=['prof', 'annee_universitaire', 'commentaire'], name='sp_prof_annee_comm_idx'),
        ),
    ]
