# Generated by Django 4.2.16 on 2026-06-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_prof_actif_alter_prof_banque'),
        ('suivi', '0012_suiviepointage_sp_prof_annee_comm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivie',
            name='prof',
            field=models.ForeignKey(blank=True, db_column='fk_prof_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivies', to='prof.prof'),
        ),
        migrations.AlterField(
            model_name='suiviepointage',
            name='prof',
            field=models.ForeignKey(blank=True, db_column='fk_prof_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.prof'),
        ),
    ]
