# Generated by Django 4.2.16 on 2026-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0016_heure_du_pointage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suivie',
            index=models.Index(fields=['departement', 'annee_universitaire', 'numero_semaine'], name='suivie_dept_annee_sem_idx'),
        ),
    ]
