# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_initial'),
        ('prof', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule_fr', models.CharField(max_length=200)),
                ('intitule_ar', models.CharField(blank=True, default='', max_length=200)),
                ('type_diplome', models.CharField(choices=[('LP', 'Licence Professionnelle'), ('LF', 'Licence Fondamentale'), ('M', 'Master'), ('ING', 'Ingénieur'), ('DUT', 'DUT')], default='LP', max_length=10)),
                ('nb_semestres', models.IntegerField(default=6)),
                ('credits_total', models.IntegerField(default=180)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres', to='parametres.institution')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_responsable', to='prof.prof')),
            ],
            options={
                'db_table': 'scolarite_filiere',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code', 'institution'], name='scolarite_f_code_c9eab9_idx'), models.Index(fields=['est_active'], name='scolarite_f_est_act_2e7646_idx')],
            },
        ),
    ]
