# Generated by Django 4.2.16 on 2026-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='type_diplome',
            field=models.CharField(choices=[('LP', 'Licence Professionnelle'), ('M', 'Master'), ('ING', 'Ingénieur'), ('Doctorat', 'Doctorat')], default='LP', max_length=10),
        ),
    ]
