# Generated by Django 6.0.3 on 2026-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0004_departementacademique_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresPonderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff_cc', models.IntegerField(default=2)),
                ('coeff_exam', models.IntegerField(default=3)),
                ('coeff_tp', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Paramètres de pondération',
                'verbose_name_plural': 'Paramètres de pondération',
                'db_table': 'scolarite_parametres_ponderation',
            },
        ),
    ]
