# Generated by Django 6.0.3 on 2026-04-24 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0005_parametres_ponderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='filiere_parent',
            field=models.ForeignKey(blank=True, help_text='Filière parente — restreint les changements administratifs aux filles de la même parente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_filles', to='scolarite.filiere'),
        ),
    ]
