# Generated by Django 6.0.3 on 2026-04-24 23:10

from django.db import migrations, models


def backfill_niveaux(apps, schema_editor):
    """
    Pour chaque filière existante, déduit niveau_fin depuis nb_semestres :
      nb_semestres = 2  → niveau_fin = 1 (1 an)
      nb_semestres = 4  → niveau_fin = 2 (2 ans = master)
      nb_semestres = 6  → niveau_fin = 3 (licence/ingénieur)
      nb_semestres = 10 → niveau_fin = 5
    niveau_debut reste à 1 par défaut (cycle complet) — l'admin ajustera manuellement
    les filières « spécialisations » qui démarrent en L2 (ex: SDID).
    """
    Filiere = apps.get_model('scolarite', 'Filiere')
    for f in Filiere.objects.all():
        nb_sem = f.nb_semestres or 6
        f.niveau_fin   = max(1, nb_sem // 2)
        f.niveau_debut = 1
        f.save(update_fields=['niveau_debut', 'niveau_fin'])


def reverse_noop(apps, schema_editor):
    pass  # rien à défaire — les colonnes sont supprimées par AddField inverse


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0006_filiere_filiere_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='niveau_debut',
            field=models.IntegerField(default=1, help_text='Premier niveau couvert par la filière (1 = L1, 2 = L2…). Tronc commun L1 = 1, spécialisation L2-L3 = 2.'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='niveau_fin',
            field=models.IntegerField(default=3, help_text='Dernier niveau couvert par la filière. Tronc commun L1 = 1, licence complète = 3, master = 2.'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='credits_total',
            field=models.IntegerField(default=180, help_text='Crédits couverts par cette filière (auto-calculé : (niveau_fin - niveau_debut + 1) × 60 si laissé à 0).'),
        ),
        migrations.RunPython(backfill_niveaux, reverse_noop),
    ]
