# Generated by Django 6.0.3 on 2026-04-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0007_add_niveau_debut_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='type_diplome',
            field=models.CharField(choices=[('LP', 'Licence'), ('M', 'Master'), ('ING', 'Ingénieur'), ('Doctorat', 'Doctorat')], default='LP', max_length=10),
        ),
    ]
