# Generated by Django 4.2.16 on 2026-06-16 17:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0008_shorten_lp_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresponderation',
            name='rattrapage_plafond',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Note maximale (sur 20) d'un EM validé en rattrapage. Défaut 10.", max_digits=4),
        ),
        migrations.AddField(
            model_name='parametresponderation',
            name='rattrapage_plafond_actif',
            field=models.BooleanField(default=True, help_text='Si activé, un EM validé grâce au rattrapage est plafonné à la valeur ci-dessous (défaut appliqué aux nouvelles sessions).'),
        ),
    ]
