# Generated by Django 4.2.16 on 2026-09-02 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salle', '0002_alter_salle_table'),
        ('prof', '0009_alter_prof_telephone'),
        ('parametres', '0015_institution_diplome_sequence_debut'),
        ('em', '0013_em_filiere_stable'),
        ('departement', '0007_fix_niveau_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_semestre', models.CharField(choices=[('I', 'Impair'), ('P', 'Pair')], default='I', max_length=1)),
                ('annee_universitaire', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(blank=True, default='', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(help_text='Groupe (ou sous-groupe) dont ceci est la grille.', on_delete=django.db.models.deletion.CASCADE, related_name='grilles_edt', to='departement.departement')),
            ],
            options={
                'db_table': 'edt_grille_type',
                'ordering': ['annee_universitaire', 'departement', 'type_semestre'],
            },
        ),
        migrations.CreateModel(
            name='SeanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametres.creneau')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_type_edt', to='em.em')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='edt.grilletype')),
                ('jour_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametres.jour')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_type_edt', to='prof.prof')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_type_edt', to='salle.salle')),
                ('type_seance_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametres.seance')),
            ],
            options={
                'db_table': 'edt_seance_type',
                'ordering': ['grille', 'jour_fk', 'creneau_fk__ordre'],
            },
        ),
        migrations.CreateModel(
            name='SeanceReelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_partage', models.UUIDField(blank=True, db_index=True, help_text="Séances d'un même cours partagé entre plusieurs groupes. Vide pour une séance ordinaire.", null=True)),
                ('origine', models.CharField(choices=[('grille', 'Dupliquée de la grille type'), ('manuelle', 'Ajoutée manuellement'), ('permutation', "Issue d'une permutation")], default='grille', max_length=12)),
                ('annulee', models.BooleanField(default=False)),
                ('observations', models.CharField(blank=True, default='', max_length=300)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('creneau_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametres.creneau')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_edt', to='departement.departement')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_edt', to='em.em')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_edt', to='prof.prof')),
                ('prof_initial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_edt_cedees', to='prof.prof')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_edt', to='salle.salle')),
                ('seance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='edt.seancetype')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_edt', to='parametres.semaine')),
                ('type_seance_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametres.seance')),
            ],
            options={
                'db_table': 'edt_seance_reelle',
                'ordering': ['semaine__date', 'creneau_fk__ordre'],
            },
        ),
        migrations.CreateModel(
            name='EmploiArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('type_semestre', models.CharField(max_length=1)),
                ('numero_semaine', models.IntegerField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('genere_le', models.DateTimeField()),
                ('jour_ref', models.IntegerField(blank=True, null=True)),
                ('creneau_ref', models.IntegerField(blank=True, null=True)),
                ('creneau_ordre', models.IntegerField(default=0)),
                ('em_ref', models.IntegerField(blank=True, null=True)),
                ('type_seance_ref', models.IntegerField(blank=True, null=True)),
                ('prof_ref', models.IntegerField(blank=True, null=True)),
                ('salle_ref', models.IntegerField(blank=True, null=True)),
                ('jour_libelle', models.CharField(blank=True, default='', max_length=30)),
                ('creneau_libelle', models.CharField(blank=True, default='', max_length=30)),
                ('departement_nom', models.CharField(blank=True, default='', max_length=100)),
                ('departement_groupe', models.CharField(blank=True, default='', max_length=30)),
                ('em_code', models.CharField(blank=True, default='', max_length=30)),
                ('em_intitule', models.CharField(blank=True, default='', max_length=200)),
                ('type_seance_libelle', models.CharField(blank=True, default='', max_length=50)),
                ('type_seance_special', models.BooleanField(default=False)),
                ('prof_nom', models.CharField(blank=True, default='', max_length=150)),
                ('prof_initial_nom', models.CharField(blank=True, default='', max_length=150)),
                ('salle_nom', models.CharField(blank=True, default='', max_length=100)),
                ('date_seance', models.DateField(blank=True, null=True)),
                ('origine', models.CharField(blank=True, default='', max_length=12)),
                ('annulee', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives_edt', to='departement.departement')),
            ],
            options={
                'verbose_name': 'Emploi du temps archivé',
                'verbose_name_plural': 'Emplois du temps archivés',
                'db_table': 'edt_emploi_archive',
                'ordering': ['-genere_le', 'jour_ref', 'creneau_ordre'],
            },
        ),
        migrations.CreateModel(
            name='DemandeLiberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('accordee', 'Accordée — salle libérée'), ('refusee', 'Refusée')], db_index=True, default='demandee', max_length=10)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.TextField(blank=True, default='')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('decidee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_liberation_decidees', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_liberation_emises', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_liberation', to='salle.salle')),
                ('seance', models.ForeignKey(help_text='La séance qui occupe la salle convoitée.', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_liberation', to='edt.seancereelle')),
            ],
            options={
                'db_table': 'edt_demande_liberation',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddConstraint(
            model_name='seancetype',
            constraint=models.UniqueConstraint(fields=('grille', 'jour_fk', 'creneau_fk'), name='uniq_edt_seance_type_case'),
        ),
        migrations.AddIndex(
            model_name='seancereelle',
            index=models.Index(fields=['semaine', 'departement'], name='edt_seance_sem_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='seancereelle',
            index=models.Index(fields=['prof', 'semaine'], name='edt_seance_prof_sem_idx'),
        ),
        migrations.AddConstraint(
            model_name='seancereelle',
            constraint=models.UniqueConstraint(fields=('departement', 'semaine', 'creneau_fk'), name='uniq_edt_seance_reelle_case'),
        ),
        migrations.AddConstraint(
            model_name='grilletype',
            constraint=models.UniqueConstraint(fields=('departement', 'type_semestre', 'annee_universitaire'), name='uniq_edt_grille'),
        ),
        migrations.AddIndex(
            model_name='emploiarchive',
            index=models.Index(fields=['annee_universitaire', 'type_semestre', 'numero_semaine', 'departement', 'version'], name='edt_archive_semaine_idx'),
        ),
        migrations.AddIndex(
            model_name='emploiarchive',
            index=models.Index(fields=['annee_universitaire', 'type_semestre', 'numero_semaine', 'prof_ref'], name='edt_archive_prof_idx'),
        ),
        migrations.AddIndex(
            model_name='emploiarchive',
            index=models.Index(fields=['annee_universitaire', 'type_semestre', 'numero_semaine', 'salle_ref'], name='edt_archive_salle_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandeliberation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'demandee')), fields=('seance', 'demandeur'), name='uniq_edt_demande_en_cours'),
        ),
    ]
