# Generated by Django 4.2.16 on 2026-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0002_origine_recopie_et_defaut_manuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancereelle',
            name='motif_annulation',
            field=models.CharField(blank=True, choices=[('', 'Manuelle'), ('ferie', 'Jour férié')], default='', max_length=10),
        ),
    ]
