# Generated by Django 4.2.16 on 2026-10-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0007_fix_niveau_nullable'),
        ('edt', '0003_motif_annulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('type_semestre', models.CharField(max_length=1)),
                ('numero_semaine', models.IntegerField()),
                ('premiere_le', models.DateTimeField(auto_now_add=True)),
                ('derniere_le', models.DateTimeField(auto_now=True)),
                ('nb_annonces', models.PositiveIntegerField(default=1)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_emploi', to='departement.departement')),
            ],
            options={
                'db_table': 'edt_annonce_emploi',
            },
        ),
        migrations.AddConstraint(
            model_name='annonceemploi',
            constraint=models.UniqueConstraint(fields=('annee_universitaire', 'type_semestre', 'numero_semaine', 'departement'), name='uniq_edt_annonce_emploi'),
        ),
    ]
