# Generated by Django 4.2.16 on 2026-10-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0017_feries_fixes_mauritanie'),
        ('absence', '0006_alter_etudiant_departement'),
        ('departement', '0007_fix_niveau_nullable'),
        ('edt', '0004_annonce_emploi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeAnglais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('rang', models.PositiveSmallIntegerField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('departement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_anglais', to='departement.departement')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes_anglais', to='parametres.niveau')),
            ],
            options={
                'db_table': 'edt_groupe_anglais',
                'ordering': ['annee_universitaire', 'niveau__niveau', 'rang'],
            },
        ),
        migrations.CreateModel(
            name='AffectationAnglais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_anglais', to='absence.etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='edt.groupeanglais')),
            ],
            options={
                'db_table': 'edt_affectation_anglais',
            },
        ),
        migrations.AddConstraint(
            model_name='groupeanglais',
            constraint=models.UniqueConstraint(fields=('niveau', 'annee_universitaire', 'rang'), name='uniq_edt_groupe_anglais_rang'),
        ),
        migrations.AddConstraint(
            model_name='groupeanglais',
            constraint=models.CheckConstraint(check=models.Q(('rang__in', [1, 2])), name='edt_groupe_anglais_deux_au_plus'),
        ),
        migrations.AddConstraint(
            model_name='affectationanglais',
            constraint=models.UniqueConstraint(fields=('etudiant', 'annee_universitaire'), name='uniq_edt_affectation_anglais'),
        ),
    ]
