# Generated by Django 4.2.16 on 2026-05-30 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily_2h', 'Quotidien 02h'), ('daily_14h', 'Quotidien 14h'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('manual', 'Manuel chiffre')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField()),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=64)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('disk_available', models.BooleanField(default=True, help_text='False quand le fichier disque a ete supprime (rotation)')),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='Date de premiere detection par le scanner')),
                ('triggered_by', models.ForeignKey(blank=True, help_text="Null = sauvegarde automatique cron, sinon user a l'origine", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupDownloadGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('granted_by', models.ForeignKey(help_text='Admin qui a accorde le droit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_download_grant',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('request_id', models.CharField(blank=True, default='', help_text='Correlation avec core_audit_log', max_length=64)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downloads', to='backup.backupartifact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_download_log',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['user', '-downloaded_at'], name='backup_down_user_id_9436fc_idx'), models.Index(fields=['artifact', '-downloaded_at'], name='backup_down_artifac_ac4b24_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='backupartifact',
            index=models.Index(fields=['type', '-created_at'], name='backup_arti_type_efe4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='backupartifact',
            index=models.Index(fields=['disk_available', '-created_at'], name='backup_arti_disk_av_664bd0_idx'),
        ),
    ]
