# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NNI', models.BigIntegerField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('type', models.CharField(choices=[('vacataire', 'Vacataire'), ('permanent', 'Permanent'), ('contractuel', 'Contractuel')], default='vacataire', max_length=20)),
                ('niveau_de_diplome', models.CharField(choices=[('Master', 'Master'), ('Ingénieur', 'Ingénieur'), ('Doctorat', 'Doctorat'), ('Autre', 'Autre')], default='Master', max_length=20)),
                ('description_dernier_diplome', models.TextField(blank=True, default='')),
                ('numero_de_compte', models.CharField(blank=True, default='', max_length=50)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='diplomes/')),
                ('grade', models.CharField(choices=[('Professeur', 'Professeur'), ('Maitre de conférences A', 'Maitre de conférences A'), ('Maitre de conférences B', 'Maitre de conférences B'), ('Maitre assistant A', 'Maitre assistant A'), ('Maitre assistant B', 'Maitre assistant B'), ('Assistant', 'Assistant'), ('Vacataire', 'Vacataire'), ('Ingénieur', 'Ingénieur'), ('Autre', 'Autre')], default='Vacataire', max_length=50)),
                ('charge', models.IntegerField(blank=True, null=True)),
                ('decharge', models.IntegerField(default=0)),
                ('banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profs', to='banque.banque')),
            ],
            options={
                'db_table': 'prof_prof',
                'ordering': ['nom'],
            },
        ),
    ]
