# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.db import migrations, models
import django.db.models.deletion

from core.migration_ops import DejaAppliqueeSurMySQL


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0002_initial'),
        ('prof', '0001_initial'),
    ]

    operations = [
        # Toutes ces operations (AlterField + AlterModelTable) sont deja en
        # place dans la DB de production MySQL (state-only, zero SQL).
        # Sur base neuve non-MySQL, elles sont executees reellement
        # (colonnes accentuees, rename prof_prof -> prof, etc.).
        DejaAppliqueeSurMySQL(
            state_operations=[
                migrations.AlterField(
                    model_name='prof',
                    name='banque',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profs', to='banque.banque'),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='charge',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='decharge',
                    field=models.PositiveIntegerField(db_column='décharge', default=0),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='description_dernier_diplome',
                    field=models.CharField(blank=True, db_column='description_dernier_diplôme', default='', max_length=200),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='grade',
                    field=models.CharField(blank=True, choices=[('Professeur', 'Professeur'), ('Maitre de conférences A', 'Maitre de conférences A'), ('Maitre de conférences B', 'Maitre de conférences B'), ('Maitre assistant A', 'Maitre assistant A'), ('Maitre assistant B', 'Maitre assistant B'), ('Assistant', 'Assistant'), ('Vacataire', 'Vacataire'), ('Ingénieur', 'Ingénieur'), ('Autre', 'Autre')], max_length=100, null=True),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='niveau_de_diplome',
                    field=models.CharField(choices=[('Master', 'Master'), ('Ingénieur', 'Ingénieur'), ('Doctorat', 'Doctorat'), ('Autre', 'Autre')], db_column='niveau_de_diplôme', default='Master', max_length=20),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='numero_de_compte',
                    field=models.CharField(blank=True, db_column='numéro_de_compte', default='', max_length=100),
                ),
                migrations.AlterField(
                    model_name='prof',
                    name='telephone',
                    field=models.PositiveIntegerField(blank=True, db_column='téléphone', null=True),
                ),
                migrations.AlterModelTable(name='prof', table='prof'),
            ],
            database_operations=[],
        ),
    ]
