# Generated by Django 4.2.16 on 2026-05-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_enseignant_role_prof_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfTypeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacataire', 'Vacataire'), ('permanent', 'Permanent'), ('contractuel', 'Contractuel'), ('militaire', 'Enseignant militaire')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('cree_par', models.CharField(blank=True, default='', max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique statut prof',
                'verbose_name_plural': 'Historique des statuts prof',
                'db_table': 'prof_type_history',
                'ordering': ['prof_id', '-date_debut'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='prof',
            name='grade',
            field=models.CharField(blank=True, choices=[('Professeur', 'Professeur'), ('Maitre de conférences A', 'Maitre de conférences A'), ('Maitre de conférences B', 'Maitre de conférences B'), ('Maitre assistant A', 'Maitre assistant A'), ('Maitre assistant B', 'Maitre assistant B'), ('Assistant', 'Assistant'), ('Vacataire', 'Vacataire'), ('Ingénieur', 'Ingénieur'), ('Autre', 'Autre'), ('Lieutenant', 'Lieutenant'), ('Capitaine', 'Capitaine'), ('Commandant', 'Commandant'), ('Lieutenant Colonel', 'Lieutenant Colonel'), ('Colonel', 'Colonel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='type',
            field=models.CharField(choices=[('vacataire', 'Vacataire'), ('permanent', 'Permanent'), ('contractuel', 'Contractuel'), ('militaire', 'Enseignant militaire')], default='vacataire', max_length=20),
        ),
    ]
