# Generated by Django 4.2.16 on 2026-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_proftypehistory_alter_prof_grade_alter_prof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='type',
            field=models.CharField(choices=[('vacataire', 'Vacataire'), ('permanent', 'Permanent'), ('contractuel', 'Contractuel'), ('militaire', 'Enseignant militaire'), ('personnel_militaire', 'Personnel militaire'), ('personnel_admin', 'Personnel administratif')], default='vacataire', max_length=20),
        ),
    ]
