# Generated by Django 4.2.16 on 2026-06-10 11:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_alter_prof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[core.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='prof',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='diplomes/', validators=[core.validators.validate_document]),
        ),
    ]
