# Generated by Django 4.2.16 on 2026-06-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0002_initial'),
        ('prof', '0006_alter_prof_cv_alter_prof_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='actif',
            field=models.BooleanField(default=True, help_text='Prof actif. Décocher pour archiver au lieu de supprimer.'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profs', to='banque.banque'),
        ),
    ]
