# Generated by Django 4.2.16 on 2026-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_heal_prof_type_history_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='telephone',
            field=models.BigIntegerField(blank=True, db_column='téléphone', null=True),
        ),
    ]
