# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('decalage', models.IntegerField(default=0)),
                ('annee_universitaire', models.CharField(blank=True, default='', max_length=20)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='parametres.niveau')),
            ],
            options={
                'db_table': 'departement_departement',
                'ordering': ['nom'],
            },
        ),
    ]
