# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.db import migrations, models
import django.db.models.deletion

from core.migration_ops import DejaAppliqueeSurMySQL


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_initial'),
        ('scolarite', '0001_initial'),
        ('departement', '0001_initial'),
    ]

    operations = [
        # La table 'departement' existe deja avec le bon nom en DB MySQL
        # (zero SQL). Sur base neuve non-MySQL, le RENAME est execute reellement.
        DejaAppliqueeSurMySQL(
            state_operations=[
                migrations.AlterModelTable(name='departement', table='departement'),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='departement',
            name='filiere',
            field=models.ForeignKey(blank=True, help_text='Filière académique stable. None pour les modules transversaux (HE, ST).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='scolarite.filiere'),
        ),
        migrations.AddField(
            model_name='departement',
            name='groupe',
            field=models.CharField(blank=True, default='', help_text="Groupe de TD : 'G1', 'G2', '' si pas de subdivision.", max_length=20),
        ),
        migrations.AddField(
            model_name='departement',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='parametres.institution'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['filiere', 'annee_universitaire'], name='departement_filiere_ae4a41_idx'),
        ),
        # No-op : deja corrige au debut (rename table -> table = aucune SQL)
        DejaAppliqueeSurMySQL(
            state_operations=[migrations.AlterModelTable(name='departement', table='departement')],
            database_operations=[],
        ),
    ]
