# Generated by Django 4.2.16 on 2026-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0003_institution_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='is_container',
            field=models.BooleanField(default=False, help_text="True = conteneur d'inscription (pas de planning), False = groupe de planification."),
        ),
    ]
