# Generated by Django 4.2.16 on 2026-05-25 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_remove_departement_decalage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='decalage_impair',
            field=models.IntegerField(default=0, help_text='Semaines sautées au début du semestre Impair (rentrée). Ex : L1 avec formation militaire de 3 semaines = 3.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='departement',
            name='decalage_pair',
            field=models.IntegerField(default=0, help_text='Semaines sautées au début du semestre Pair (rare : stage, examens reportés…). Mettre 0 si non applicable.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
