# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('capacite', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'salle_salle',
                'ordering': ['nom'],
            },
        ),
    ]
