# Generated by Django 4.2.16 on 2026-04-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salle',
            table='salle',
        ),
    ]
