# Generated by Django 4.2.16 on 2026-04-14 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0002_etudiant_adresse_ar_etudiant_adresse_fr_etudiant_cni_and_more'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('attestation_inscription', "Attestation d'inscription"), ('releve_semestre', 'Relevé de notes (semestre)'), ('releve_complet', 'Relevé de notes complet'), ('attestation_reussite', 'Attestation de réussite'), ('diplome', 'Diplôme')], max_length=40)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('token_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('annee_universitaire', models.CharField(blank=True, default='', max_length=10)),
                ('hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('est_valide', models.BooleanField(default=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='documents/officiels/')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_officiels', to='absence.etudiant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generes', to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametres.semestre')),
            ],
            options={
                'db_table': 'documents_officiel',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='RegistreDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diplome', models.CharField(max_length=50, unique=True)),
                ('mention', models.CharField(blank=True, default='', max_length=50)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_delivrance', models.DateField()),
                ('annee_universitaire', models.CharField(max_length=10)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registre_diplome', to='documents.documentofficiel')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='absence.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='scolarite.filiere')),
            ],
            options={
                'db_table': 'documents_registre_diplome',
                'ordering': ['-date_delivrance'],
            },
        ),
    ]
