# Generated by Django 6.0.3 on 2026-04-15 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('parametres', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSerieConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('attestation_inscription', "Attestation d'inscription"), ('releve_semestre', 'Relevé de notes (semestre)'), ('releve_complet', 'Relevé de notes complet'), ('attestation_reussite', 'Attestation de réussite'), ('diplome', 'Diplôme')], max_length=40)),
                ('prefixe', models.CharField(max_length=10)),
                ('dernier_numero', models.IntegerField(default=0)),
                ('nb_chiffres', models.IntegerField(default=5)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_numerotation', to='parametres.institution')),
            ],
            options={
                'db_table': 'documents_numero_serie_config',
                'unique_together': {('institution', 'type_document')},
            },
        ),
    ]
