# Generated by Django 4.2.16 on 2026-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_institution_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofficiel',
            name='premiere_generation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
