# Generated by Django 4.2.16 on 2026-06-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentofficiel_premiere_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofficiel',
            name='type_document',
            field=models.CharField(choices=[('attestation_inscription', "Attestation d'inscription"), ('releve_semestre', 'Relevé de notes (semestre)'), ('releve_complet', 'Relevé de notes complet'), ('attestation_reussite', 'Attestation de réussite'), ('attestation_diplome', 'Attestation de diplôme'), ('diplome', 'Diplôme')], max_length=40),
        ),
        migrations.AlterField(
            model_name='numeroserieconfig',
            name='type_document',
            field=models.CharField(choices=[('attestation_inscription', "Attestation d'inscription"), ('releve_semestre', 'Relevé de notes (semestre)'), ('releve_complet', 'Relevé de notes complet'), ('attestation_reussite', 'Attestation de réussite'), ('attestation_diplome', 'Attestation de diplôme'), ('diplome', 'Diplôme')], max_length=40),
        ),
    ]
