# Generated by Django 4.2.16 on 2026-07-13 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0015_institution_diplome_sequence_debut'),
        ('prof', '0009_alter_prof_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_alter_documentofficiel_type_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_document', models.CharField(blank=True, default='', max_length=60)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('token_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('annee_universitaire', models.CharField(blank=True, default='', max_length=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heures_eq_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('est_valide', models.BooleanField(default=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_travail_generees', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attestations_travail', to='parametres.institution')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations_travail', to='prof.prof')),
            ],
            options={
                'db_table': 'documents_attestation_travail',
                'ordering': ['-date_generation'],
            },
        ),
    ]
