# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau', models.CharField(max_length=100, unique=True)),
                ('duree', models.FloatField(default=1.5)),
                ('type_creneau', models.CharField(choices=[('matin', 'Matin'), ('apres-midi', 'Après-midi'), ('soir', 'Soir')], default='matin', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('is_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parametres_creneau',
                'ordering': ['ordre', 'creneau'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronyme', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'parametres_institution',
            },
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'parametres_jour',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'parametres_niveau',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='Ramadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'db_table': 'parametres_ramadan',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'parametres_seance',
                'ordering': ['type_seance'],
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semaine', models.IntegerField()),
                ('jour', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('type_semestre', models.CharField(default='I', max_length=1)),
            ],
            options={
                'db_table': 'parametres_semaine',
                'ordering': ['annee_universitaire', 'numero_semaine', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'parametres_year',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_semestre', models.CharField(max_length=20)),
                ('semestre', models.CharField(max_length=100)),
                ('type_semestre', models.CharField(choices=[('P', 'Pair'), ('I', 'Impair')], default='I', max_length=1)),
                ('niveau_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='parametres.niveau')),
            ],
            options={
                'db_table': 'parametres_semestre',
                'ordering': ['code_semestre'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('taux', models.FloatField()),
                ('date_debut', models.DateField()),
            ],
            options={
                'db_table': 'parametres_paiement',
                'ordering': ['type', '-date_debut'],
                'unique_together': {('type', 'date_debut')},
            },
        ),
    ]
