# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.db import migrations, models
import django.db.models.deletion

from core.migration_ops import DejaAppliqueeSurMySQL


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        # Corrige l'etat Django pour les tables pas encore fixes en 0002.
        # La table 'annee' doit etre connue AVANT le AddField(year.*).
        # Sur MySQL : les tables de prod ont deja les bons noms — zero SQL.
        # Sur base neuve non-MySQL : RENAME executes reellement.
        DejaAppliqueeSurMySQL(
            state_operations=[
                migrations.AlterModelTable(name='year',       table='annee'),
                migrations.AlterModelTable(name='creneau',    table='creneau'),
                migrations.AlterModelTable(name='jour',       table='jour'),
                migrations.AlterModelTable(name='niveau',     table='niveau'),
                migrations.AlterModelTable(name='paiement',   table='paiement'),
                migrations.AlterModelTable(name='seance',     table='Seance'),
                migrations.AlterModelTable(name='semaine',    table='semaine'),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='semestre',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres', to='scolarite.filiere'),
        ),
        migrations.AddField(
            model_name='year',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='est_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='year',
            name='est_cloturee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='creneau',
            table='creneau',
        ),
        migrations.AlterModelTable(
            name='institution',
            table='institution',
        ),
        migrations.AlterModelTable(
            name='jour',
            table='jour',
        ),
        migrations.AlterModelTable(
            name='niveau',
            table='niveau',
        ),
        migrations.AlterModelTable(
            name='paiement',
            table='paiement',
        ),
        migrations.AlterModelTable(
            name='seance',
            table='Seance',
        ),
        migrations.AlterModelTable(
            name='semaine',
            table='semaine',
        ),
        migrations.AlterModelTable(
            name='semestre',
            table='semestre',
        ),
        migrations.AlterModelTable(
            name='year',
            table='annee',
        ),
    ]
