# Generated by Django 4.2.16 on 2026-04-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='groupe_ar',
            field=models.CharField(blank=True, default='', help_text='Organisation de tutelle en arabe (ex: مجمع بوليتكنيك)', max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='groupe_fr',
            field=models.CharField(blank=True, default='', help_text='Organisation de tutelle (ex: Groupe Polytechnique)', max_length=200),
        ),
    ]
