# Generated by Django 6.0.3 on 2026-05-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_semaine_jour_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaine',
            name='annee_universitaire',
            field=models.CharField(max_length=9),
        ),
    ]
