# Generated by Django 4.2.16 on 2026-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_alter_semaine_annee_universitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
