# Generated by Django 4.2.16 on 2026-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_seed_special_seances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semaine',
            options={'ordering': ['annee_universitaire', 'type_semestre', 'date']},
        ),
        migrations.AddField(
            model_name='semaine',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='semaine',
            name='type_semaine',
            field=models.CharField(choices=[('cours', 'Cours'), ('ferie', 'Férié'), ('vacances', 'Vacances'), ('examen', 'Examens')], default='cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='numero_semaine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
