# Generated by Django 4.2.16 on 2026-06-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0011_alter_semaine_options_semaine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='niveau_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semestres', to='parametres.niveau'),
        ),
    ]
