# Generated by Django 4.2.16 on 2026-06-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0012_alter_semestre_niveau_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='commandant_nom_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='commandant_nom_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='commandant_signature',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/signatures/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='commandant_titre_ar',
            field=models.CharField(blank=True, default='قائد مجمع بوليتكنيك', max_length=150),
        ),
        migrations.AddField(
            model_name='institution',
            name='commandant_titre_fr',
            field=models.CharField(blank=True, default='Le Commandant du Groupe Polytechnique', max_length=150),
        ),
    ]
