# Generated by Django 4.2.16 on 2026-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0013_institution_commandant_nom_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo_groupe',
            field=models.ImageField(blank=True, help_text='Logo du Groupe de tutelle (ex: Groupe Polytechnique) — affiché en haut à gauche des attestations de diplôme.', null=True, upload_to='institutions/logos/'),
        ),
    ]
