# Generated by Django 4.2.16 on 2026-07-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0014_institution_logo_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='diplome_sequence_debut',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
