# Generated by Django 4.2.16 on 2026-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0015_institution_diplome_sequence_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerieFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('libelle', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parametres_jour_ferie_fixe',
                'ordering': ['mois', 'jour'],
            },
        ),
        migrations.AddConstraint(
            model_name='jourferiefixe',
            constraint=models.UniqueConstraint(fields=('jour', 'mois'), name='uniq_jour_ferie_fixe_jour_mois'),
        ),
    ]
