# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em', '0001_initial'),
        ('parametres', '0001_initial'),
        ('prof', '0001_initial'),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.FloatField(default=1.5)),
                ('date', models.DateField()),
                ('annee_univ', models.CharField(max_length=20)),
                ('taux_paiement', models.FloatField(default=0.0)),
                ('departements', models.ManyToManyField(blank=True, related_name='vacations', to='departement.departement')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacations', to='em.em')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='prof.prof')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacations', to='parametres.seance')),
            ],
            options={
                'db_table': 'vacation_vacation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.FloatField(default=2.0)),
                ('date', models.DateField()),
                ('annee_univ', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to='departement.departement')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to='prof.prof')),
            ],
            options={
                'db_table': 'vacation_surveillance',
                'ordering': ['-date'],
            },
        ),
    ]
