# Generated by Django 4.2.16 on 2026-06-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_prof_actif_alter_prof_banque'),
        ('vacation', '0002_add_institution_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillance',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveillances', to='prof.prof'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacations', to='prof.prof'),
        ),
    ]
