# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('ajourned', 'Ajourné'), ('rachat', 'Admis par rachat'), ('exclus', 'Exclus')], max_length=20)),
                ('moyenne_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credits_annuels', models.IntegerField(default=0)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'evaluations_ligne_deliberation',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_note', models.CharField(choices=[('CC', 'Contrôle continu'), ('TP', 'Travaux pratiques'), ('EXAM', 'Examen final')], max_length=10)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Note sur 20.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluations_note',
            },
        ),
        migrations.CreateModel(
            name='PVDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(help_text="Année d'étude : 1, 2, 3")),
                ('date_deliberation', models.DateField()),
                ('est_clos', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'evaluations_pv_deliberation',
            },
        ),
        migrations.CreateModel(
            name='ResultatElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('est_valide', models.BooleanField(default=False)),
                ('est_eliminatoire', models.BooleanField(default=False, help_text="True si note < seuil_eliminatoire de l'élément.")),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluations_resultat_element',
            },
        ),
        migrations.CreateModel(
            name='ResultatSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credits_valides', models.IntegerField(default=0)),
                ('est_admis', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluations_resultat_semestre',
            },
        ),
        migrations.CreateModel(
            name='SessionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_session', models.CharField(choices=[('normale', 'Session normale'), ('rattrapage', 'Session de rattrapage')], default='normale', max_length=20)),
                ('date_debut_saisie', models.DateTimeField()),
                ('date_cloture_saisie', models.DateTimeField()),
                ('est_close', models.BooleanField(default=False)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_evaluation', to='parametres.year')),
                ('cloturee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_cloturees', to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(blank=True, help_text='null = session commune à tous les semestres.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_evaluation', to='parametres.semestre')),
            ],
            options={
                'db_table': 'evaluations_session',
                'ordering': ['-annee_univ', 'type_session'],
            },
        ),
    ]
