# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0001_initial'),
        ('scolarite', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatsemestre',
            name='inscription_ped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_semestre', to='inscriptions.inscriptionpedagogique'),
        ),
        migrations.AddField(
            model_name='resultatsemestre',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_semestre', to='evaluations.sessionevaluation'),
        ),
        migrations.AddField(
            model_name='resultatelement',
            name='inscription_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='inscriptions.inscriptionelement'),
        ),
        migrations.AddField(
            model_name='resultatelement',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_elements', to='evaluations.sessionevaluation'),
        ),
        migrations.AddField(
            model_name='pvdeliberation',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvs', to='scolarite.filiere'),
        ),
        migrations.AddField(
            model_name='pvdeliberation',
            name='president_jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvs_presides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvdeliberation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvs', to='evaluations.sessionevaluation'),
        ),
        migrations.AddField(
            model_name='note',
            name='inscription_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='inscriptions.inscriptionelement'),
        ),
        migrations.AddField(
            model_name='note',
            name='saisie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='evaluations.sessionevaluation'),
        ),
        migrations.AddField(
            model_name='lignedeliberation',
            name='inscription_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_deliberation', to='inscriptions.inscriptionadministrative'),
        ),
        migrations.AddField(
            model_name='lignedeliberation',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='evaluations.pvdeliberation'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionevaluation',
            unique_together={('annee_univ', 'type_session', 'semestre')},
        ),
        migrations.AlterUniqueTogether(
            name='resultatsemestre',
            unique_together={('inscription_ped', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='pvdeliberation',
            unique_together={('session', 'filiere', 'niveau')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['session', 'type_note'], name='evaluations_session_d9a6f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('inscription_element', 'session', 'type_note')},
        ),
        migrations.AlterUniqueTogether(
            name='lignedeliberation',
            unique_together={('pv', 'inscription_admin')},
        ),
    ]
