# Generated by Django 6.0.3 on 2026-04-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
        ('parametres', '0003_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sessionevaluation',
            name='est_ouverte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionevaluation',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_evaluation', to='scolarite.filiere'),
        ),
        migrations.AddField(
            model_name='sessionevaluation',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sessionevaluation',
            name='annee_univ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_evaluation', to='parametres.year'),
        ),
        migrations.AlterField(
            model_name='sessionevaluation',
            name='date_cloture_saisie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionevaluation',
            name='date_debut_saisie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
