# Generated by Django 4.2.16 on 2026-04-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_initial'),
        ('scolarite', '0001_initial'),
        ('evaluations', '0003_sessionevaluation_code_sessionevaluation_est_ouverte_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionevaluation',
            unique_together={('annee_univ', 'filiere', 'type_session', 'semestre')},
        ),
    ]
