# Generated by Django 6.0.3 on 2026-04-15 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_fix_unique_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_validation_module', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('seuil_validation_semestre', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('seuil_compensation', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('seuil_eliminatoire', models.DecimalField(decimal_places=2, default=6, max_digits=4)),
                ('justification', models.TextField(blank=True, default='')),
                ('pv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametre_jury', to='evaluations.pvdeliberation')),
            ],
            options={
                'db_table': 'evaluations_parametre_jury',
            },
        ),
        migrations.CreateModel(
            name='RachatNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nouvelle_valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motif', models.TextField()),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('decidee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rachats_decides', to=settings.AUTH_USER_MODEL)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rachats', to='evaluations.lignedeliberation')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rachats', to='evaluations.pvdeliberation')),
            ],
            options={
                'db_table': 'evaluations_rachat_note',
                'indexes': [models.Index(fields=['pv'], name='evaluations_pv_id_f619e1_idx'), models.Index(fields=['ligne'], name='evaluations_ligne_i_d48e99_idx')],
            },
        ),
    ]
