# Generated by Django 6.0.3 on 2026-04-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_dedup_sessions_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevaluation',
            options={'ordering': ['-annee_univ', 'type_semestre', 'type_session']},
        ),
    ]
