# Generated by Django 6.0.3 on 2026-04-20 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_alter_sessionevaluation_options'),
        ('inscriptions', '0005_add_em_fk_to_inscriptionelement'),
        ('modules', '0001_initial'),
        ('parametres', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pvdeliberation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lignedeliberation',
            name='code_statut',
            field=models.CharField(blank=True, choices=[('V', 'Validé directement (Art. 12)'), ('VCI', 'Validé par Compensation Interne — module (Art. 13)'), ('VCS', 'Validé par Compensation Semestrielle (Art. 14)'), ('R', 'Validé par Rachat jury'), ('NV', 'Non Validé — rattrapage facultatif (Art. 17 al. 3)'), ('NVO', 'Non Validé — rattrapage obligatoire (Art. 17 al. 2)'), ('E', 'Éliminatoire — rattrapage obligatoire (Art. 17 al. 1)')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='lignedeliberation',
            name='decision_annuelle',
            field=models.CharField(blank=True, choices=[('passage_droit', 'Admis — passage de droit (60 crédits)'), ('passage_cond', 'Admis conditionnel (≥ 65 % crédits)'), ('redoublement', 'Redoublement autorisé (Art. 21-22)'), ('exclusion', 'Exclu (Art. 21)'), ('annee_blanche', 'Année blanche — absence médicale (Art. 23)')], default='', help_text='Décision de progression annuelle (PV annuel uniquement).', max_length=20),
        ),
        migrations.AddField(
            model_name='lignedeliberation',
            name='taux_capitalisation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="% crédits capitalisés sur crédits de l'année (Art. 20).", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lignedeliberation',
            name='verrou_l3',
            field=models.BooleanField(default=False, help_text='True si passage en L3 bloqué par L1 non entièrement validée (Art. 20).'),
        ),
        migrations.AddField(
            model_name='pvdeliberation',
            name='annee_univ',
            field=models.ForeignKey(blank=True, help_text='Année universitaire (obligatoire pour PV annuel).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pvs_annuels', to='parametres.year'),
        ),
        migrations.AddField(
            model_name='pvdeliberation',
            name='semestre_code',
            field=models.CharField(blank=True, default='', help_text='Code semestre pour PV semestriel (ex : S1, S2).', max_length=10),
        ),
        migrations.AddField(
            model_name='pvdeliberation',
            name='type_pv',
            field=models.CharField(choices=[('semestriel', 'Délibération semestrielle'), ('annuel', 'Délibération annuelle (progression)')], default='semestriel', help_text='Nature du PV : semestriel (Art. 15) ou annuel (Art. 20).', max_length=20),
        ),
        migrations.AddField(
            model_name='resultatelement',
            name='code_statut',
            field=models.CharField(blank=True, choices=[('V', 'Validé directement (Art. 12)'), ('VCI', 'Validé par Compensation Interne — module (Art. 13)'), ('VCS', 'Validé par Compensation Semestrielle (Art. 14)'), ('R', 'Validé par Rachat jury'), ('NV', 'Non Validé — rattrapage facultatif (Art. 17 al. 3)'), ('NVO', 'Non Validé — rattrapage obligatoire (Art. 17 al. 2)'), ('E', 'Éliminatoire — rattrapage obligatoire (Art. 17 al. 1)')], default='', help_text="Statut d'évaluation (V/VCI/VCS/R/NV/NVO/E) — docs/deliberation.md §2.", max_length=3),
        ),
        migrations.AddField(
            model_name='resultatsemestre',
            name='code_statut',
            field=models.CharField(blank=True, choices=[('V', 'Validé directement (Art. 12)'), ('VCI', 'Validé par Compensation Interne — module (Art. 13)'), ('VCS', 'Validé par Compensation Semestrielle (Art. 14)'), ('R', 'Validé par Rachat jury'), ('NV', 'Non Validé — rattrapage facultatif (Art. 17 al. 3)'), ('NVO', 'Non Validé — rattrapage obligatoire (Art. 17 al. 2)'), ('E', 'Éliminatoire — rattrapage obligatoire (Art. 17 al. 1)')], default='', help_text='Statut du semestre (V/VCS/R/NV).', max_length=3),
        ),
        migrations.AlterField(
            model_name='pvdeliberation',
            name='session',
            field=models.ForeignKey(blank=True, help_text="Session d'évaluation (obligatoire pour PV semestriel).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pvs', to='evaluations.sessionevaluation'),
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'Président (responsable de filière)'), ('chef_etablissement', "Chef d'établissement"), ('enseignant', 'Enseignant permanent'), ('professionnel', 'Enseignant issu du milieu professionnel'), ('secretaire', 'Secrétaire (scolarité)')], max_length=30)),
                ('signature_at', models.DateTimeField(blank=True, null=True)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_jury', to='evaluations.pvdeliberation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jury_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluations_membre_jury',
                'unique_together': {('pv', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ObligationRattrapage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_obligation', models.CharField(choices=[('obligatoire', 'Rattrapage obligatoire'), ('facultatif', 'Rattrapage facultatif')], max_length=20)),
                ('code_statut_initial', models.CharField(blank=True, choices=[('V', 'Validé directement (Art. 12)'), ('VCI', 'Validé par Compensation Interne — module (Art. 13)'), ('VCS', 'Validé par Compensation Semestrielle (Art. 14)'), ('R', 'Validé par Rachat jury'), ('NV', 'Non Validé — rattrapage facultatif (Art. 17 al. 3)'), ('NVO', 'Non Validé — rattrapage obligatoire (Art. 17 al. 2)'), ('E', 'Éliminatoire — rattrapage obligatoire (Art. 17 al. 1)')], default='', help_text="Code de l'élément avant rattrapage (E/NVO/NV).", max_length=3)),
                ('motif', models.TextField(blank=True, default='')),
                ('inscription_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations_rattrapage', to='inscriptions.inscriptionelement')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_rattrapage', to='evaluations.lignedeliberation')),
            ],
            options={
                'db_table': 'evaluations_obligation_rattrapage',
                'unique_together': {('ligne', 'inscription_element')},
            },
        ),
        migrations.CreateModel(
            name='ResultatModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credits_valides', models.IntegerField(default=0)),
                ('est_valide', models.BooleanField(default=False)),
                ('a_eliminatoire', models.BooleanField(default=False, help_text='True si au moins un élément du module a une moyenne éliminatoire.')),
                ('code_statut', models.CharField(blank=True, choices=[('V', 'Validé directement (Art. 12)'), ('VCI', 'Validé par Compensation Interne — module (Art. 13)'), ('VCS', 'Validé par Compensation Semestrielle (Art. 14)'), ('R', 'Validé par Rachat jury'), ('NV', 'Non Validé — rattrapage facultatif (Art. 17 al. 3)'), ('NVO', 'Non Validé — rattrapage obligatoire (Art. 17 al. 2)'), ('E', 'Éliminatoire — rattrapage obligatoire (Art. 17 al. 1)')], default='', help_text='Statut du module (V/VCI/VCS/R/NV/NVO/E).', max_length=3)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('inscription_ped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_module', to='inscriptions.inscriptionpedagogique')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='modules.module')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_modules', to='evaluations.sessionevaluation')),
            ],
            options={
                'db_table': 'evaluations_resultat_module',
                'unique_together': {('inscription_ped', 'module', 'session')},
            },
        ),
    ]
