# Generated by Django 6.0.3 on 2026-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_alter_pvdeliberation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvdeliberation',
            name='date_deliberation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
