# Generated by Django 6.0.3 on 2026-04-24 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_resultat_element_fk_anonymat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignedeliberation',
            old_name='verrou_l3',
            new_name='verrou_passage',
        ),
        migrations.AlterField(
            model_name='lignedeliberation',
            name='verrou_passage',
            field=models.BooleanField(default=False, help_text='True si passage bloqué : Licence (L3 nécessite L1 complète Art. 20) ou Ingénieur (S5 nécessite S1+S2 complets Art. 25).'),
        ),
        migrations.AddField(
            model_name='parametrejury',
            name='seuil_progression',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override seuil de progression annuelle (% crédits). NULL = défaut réglementaire (65 LP / 75 ING).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='anonymatsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='JustificatifAnneeBlanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='justificatifs_annee_blanche/%Y/')),
                ('motif', models.TextField()),
                ('date_decision', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('decide_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annees_blanches_decidees', to=settings.AUTH_USER_MODEL)),
                ('ligne_deliberation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='justificatif_annee_blanche', to='evaluations.lignedeliberation')),
            ],
            options={
                'db_table': 'evaluations_justificatif_annee_blanche',
            },
        ),
    ]
