# Generated by Django 4.2.16 on 2026-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_add_institution_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='rattrapage_plafond',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sessionevaluation',
            name='rattrapage_plafond_actif',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
