# Generated by Django 4.2.16 on 2026-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_sessionevaluation_rattrapage_plafond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='rattrapage_vcs_actif',
            field=models.BooleanField(default=False),
        ),
    ]
