# Generated by Django 4.2.16 on 2026-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_sessionevaluation_rattrapage_vcs_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='rattrapage_vci_actif',
            field=models.BooleanField(default=False),
        ),
    ]
