# Generated by Django 4.2.16 on 2026-03-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em', '0001_initial'),
        ('prof', '0001_initial'),
        ('salle', '0001_initial'),
        ('parametres', '0001_initial'),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploisArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prof', models.CharField(blank=True, max_length=50)),
                ('id_em', models.CharField(blank=True, max_length=50)),
                ('type_seance', models.CharField(blank=True, max_length=50)),
                ('jour', models.CharField(blank=True, max_length=20)),
                ('creneau', models.CharField(blank=True, max_length=100)),
                ('id_salle', models.CharField(blank=True, max_length=50)),
                ('id_departement', models.CharField(blank=True, max_length=50)),
                ('id_semestre', models.CharField(blank=True, max_length=50)),
                ('annee_universitaire', models.CharField(blank=True, max_length=20)),
                ('type_semestre', models.CharField(blank=True, max_length=1)),
                ('taux_paiement', models.FloatField(default=0.0)),
                ('creneau_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.creneau')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departement.departement')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='em.em')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.prof')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salle.salle')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.semestre')),
            ],
            options={
                'db_table': 'emplois_emploisarchive',
            },
        ),
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prof', models.CharField(blank=True, db_index=True, max_length=50)),
                ('id_em', models.CharField(blank=True, max_length=50)),
                ('type_seance', models.CharField(blank=True, max_length=50)),
                ('jour', models.CharField(blank=True, max_length=20)),
                ('creneau', models.CharField(blank=True, max_length=100)),
                ('id_salle', models.CharField(blank=True, max_length=50)),
                ('id_departement', models.CharField(blank=True, db_index=True, max_length=50)),
                ('id_semestre', models.CharField(blank=True, max_length=50)),
                ('annee_universitaire', models.CharField(blank=True, db_index=True, max_length=20)),
                ('type_semestre', models.CharField(blank=True, max_length=1)),
                ('taux_paiement', models.FloatField(default=0.0)),
                ('creneau_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='parametres.creneau')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='departement.departement')),
                ('em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='em.em')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='prof.prof')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='salle.salle')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='parametres.semestre')),
            ],
            options={
                'db_table': 'emplois_emplois',
            },
        ),
    ]
