# Generated by Django 4.2.16 on 2026-04-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0002_etudiant_adresse_ar_etudiant_adresse_fr_etudiant_cni_and_more'),
        ('prof', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_nom', models.CharField(max_length=200)),
                ('entreprise_adresse', models.TextField(blank=True, default='')),
                ('tuteur_entreprise', models.CharField(blank=True, default='', max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('sujet', models.CharField(max_length=500)),
                ('convention_fichier', models.FileField(blank=True, null=True, upload_to='stages/conventions/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('est_pfe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conventions_stage', to='absence.etudiant')),
                ('tuteur_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_tuteur', to='prof.prof')),
            ],
            options={
                'db_table': 'stages_convention',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_entreprise', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_rapport', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_soutenance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('est_valide_pfe', models.BooleanField(default=False)),
                ('date_soutenance', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
                ('convention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='stages.conventionstage')),
                ('jury', models.ManyToManyField(blank=True, related_name='evaluations_jury', to='prof.prof')),
            ],
            options={
                'db_table': 'stages_evaluation',
            },
        ),
        migrations.CreateModel(
            name='DerogationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='stages/derogations/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='soumise', max_length=20)),
                ('decision_motif', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derogations', to='absence.etudiant')),
            ],
            options={
                'db_table': 'stages_derogation',
                'ordering': ['-created_at'],
            },
        ),
    ]
