# Generated by Django 4.2.16 on 2026-06-10 15:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventionstage',
            name='convention_fichier',
            field=models.FileField(blank=True, null=True, upload_to='stages/conventions/', validators=[core.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='derogationmedicale',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='stages/derogations/', validators=[core.validators.validate_document]),
        ),
    ]
