# Generated by Django 6.0.3 on 2026-04-18 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0004_etudiant_user_alter_etudiant_statut'),
        ('evaluations', '0008_alter_sessionevaluation_options'),
        ('inscriptions', '0005_add_em_fk_to_inscriptionelement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reclamation', models.CharField(choices=[('absence', 'Absence'), ('note', 'Note'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20)),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='reclamations/justificatifs/')),
                ('reponse', models.TextField(blank=True, default='')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='absence.etudiant')),
                ('inscription_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='inscriptions.inscriptionelement')),
                ('presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='absence.presence')),
                ('session_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='evaluations.sessionevaluation')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclamations_reclamation',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
