# Generated by Django 6.0.3 on 2026-04-29 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_semestre_simplification'),
        ('reclamations', '0001_initial'),
        ('scolarite', '0008_shorten_lp_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_session', models.CharField(choices=[('normale', 'Normale (SN)'), ('rattrapage', 'Rattrapage (SR)')], default='rattrapage', max_length=20)),
                ('type_semestre', models.CharField(choices=[('I', 'Impairs (S1 / S3 / S5)'), ('P', 'Pairs (S2 / S4 / S6)')], max_length=1)),
                ('niveau', models.IntegerField(blank=True, help_text='Si vide : tous les niveaux.', null=True)),
                ('date_ouverture', models.DateTimeField()),
                ('date_fermeture', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('motif', models.CharField(blank=True, default='', help_text="Texte court affiche aux etudiants (ex : 'Reclamation SR-I 2025-2026').", max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes_reclamation', to='parametres.year')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_reclamation_creees', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, help_text="Si vide : toutes les filieres de l'institution.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodes_reclamation', to='scolarite.filiere')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes_reclamation', to='parametres.institution')),
            ],
            options={
                'db_table': 'reclamations_periode',
                'ordering': ['-date_ouverture'],
                'indexes': [models.Index(fields=['actif', 'date_ouverture', 'date_fermeture'], name='reclamation_actif_cb6dd5_idx'), models.Index(fields=['annee_univ', 'type_semestre'], name='reclamation_annee_u_a44774_idx')],
            },
        ),
    ]
