# Generated by Django 4.2.16 on 2026-06-10 15:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_periodereclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='reclamations/justificatifs/', validators=[core.validators.validate_document]),
        ),
    ]
