# Generated by Django 4.2.16 on 2026-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_reclamation_sans_cle_etrangere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointage_id', models.BigIntegerField(db_index=True)),
                ('prof_id', models.BigIntegerField(db_index=True)),
                ('prof_nom', models.CharField(blank=True, default='', max_length=200)),
                ('annee_universitaire', models.CharField(blank=True, default='', max_length=20)),
                ('numero_semaine', models.IntegerField(blank=True, null=True)),
                ('jour', models.CharField(blank=True, default='', max_length=20)),
                ('creneau', models.CharField(blank=True, default='', max_length=50)),
                ('type_seance', models.CharField(blank=True, default='', max_length=50)),
                ('em_id', models.BigIntegerField(blank=True, null=True)),
                ('em_code', models.CharField(blank=True, default='', max_length=50)),
                ('em_intitule', models.CharField(blank=True, default='', max_length=200)),
                ('salle_nom', models.CharField(blank=True, default='', max_length=100)),
                ('groupes', models.CharField(blank=True, default='', max_length=500)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('reponse', models.TextField(blank=True, default='')),
                ('traitee_par_id', models.BigIntegerField(blank=True, null=True)),
                ('traitee_par_nom', models.CharField(blank=True, default='', max_length=150)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reclamations_reclamation_seance',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
