# Generated by Django 4.2.16 on 2026-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaisieNoteEnLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField(db_index=True)),
                ('inscription_element_id', models.BigIntegerField(db_index=True)),
                ('em_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('etudiant_id', models.BigIntegerField(blank=True, null=True)),
                ('session_libelle', models.CharField(blank=True, default='', max_length=200)),
                ('em_code', models.CharField(blank=True, default='', max_length=50)),
                ('em_intitule', models.CharField(blank=True, default='', max_length=200)),
                ('etudiant_matricule', models.CharField(blank=True, default='', max_length=50)),
                ('etudiant_nom', models.CharField(blank=True, default='', max_length=200)),
                ('cc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saisi_par_id', models.BigIntegerField(blank=True, null=True)),
                ('saisi_par_nom', models.CharField(blank=True, default='', max_length=150)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saisie_note_en_ligne',
                'ordering': ['em_code', 'etudiant_matricule'],
            },
        ),
        migrations.AddConstraint(
            model_name='saisienoteenligne',
            constraint=models.UniqueConstraint(fields=('session_id', 'inscription_element_id'), name='saisie_en_ligne_unique_par_inscription'),
        ),
    ]
