# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        ('parametres', '0003_initial'),
        ('absence', '0002_etudiant_adresse_ar_etudiant_adresse_fr_etudiant_cni_and_more'),
        ('em', '0002_em_coefficient_em_credits_em_est_element_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(help_text="Année d'étude : 1, 2, 3, ...")),
                ('numero_inscription', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('montant_frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_payee', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('recu_paiement', models.CharField(blank=True, default='', max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_admin', to='parametres.year')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_admin', to='absence.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_admin', to='scolarite.filiere')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_admin_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inscriptions_administrative',
            },
        ),
        migrations.CreateModel(
            name='InscriptionPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_redoublant', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('inscription_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_ped', to='inscriptions.inscriptionadministrative')),
                ('semestre', models.ForeignKey(help_text='Semestre étendu : filiere + annee_univ remplis.', on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_ped', to='parametres.semestre')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_ped_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inscriptions_pedagogique',
                'unique_together': {('inscription_admin', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Mauritanienne', max_length=50)),
                ('cni', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bac_serie', models.CharField(max_length=50)),
                ('bac_annee', models.IntegerField()),
                ('bac_mention', models.CharField(blank=True, default='', max_length=50)),
                ('bac_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_examen', 'En examen'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée'), ('inscrite', 'Inscrite')], default='soumise', max_length=20)),
                ('motif_rejet', models.TextField(blank=True, default='')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_examen', models.DateTimeField(blank=True, null=True)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='parametres.year')),
                ('examinee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscriptions_examinees', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='scolarite.filiere')),
            ],
            options={
                'db_table': 'inscriptions_preinscription',
                'ordering': ['-date_soumission'],
                'indexes': [models.Index(fields=['statut', 'annee_univ'], name='inscription_statut_d93663_idx'), models.Index(fields=['numero_dossier'], name='inscription_numero__8c788a_idx'), models.Index(fields=['cni'], name='inscription_cni_e207dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='InscriptionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_dette', models.BooleanField(default=False, help_text="True si l'étudiant repassé cet élément d'une année antérieure.")),
                ('annee_dette', models.ForeignKey(blank=True, help_text="Année académique d'origine de la dette.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_dettes', to='parametres.year')),
                ('element', models.ForeignKey(help_text='EM avec est_element_module=True.', on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_elements', to='em.em')),
                ('inscription_ped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_elements', to='inscriptions.inscriptionpedagogique')),
            ],
            options={
                'db_table': 'inscriptions_element',
                'unique_together': {('inscription_ped', 'element')},
            },
        ),
        migrations.AddIndex(
            model_name='inscriptionadministrative',
            index=models.Index(fields=['annee_univ', 'filiere', 'statut'], name='inscription_annee_u_e9b0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionadministrative',
            index=models.Index(fields=['numero_inscription'], name='inscription_numero__476a2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionadministrative',
            unique_together={('etudiant', 'annee_univ')},
        ),
    ]
