# Generated by Django 6.0.3 on 2026-04-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
        ('parametres', '0003_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscription',
            name='bac_annee',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='bac_mention',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='bac_serie',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='prenom',
        ),
        migrations.AddField(
            model_name='preinscription',
            name='annee_bac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='mention_bac',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='motif',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='nom_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='nom_fr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='preinscriptions/photos/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='preinscriptions/identite/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='prenom_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='prenom_fr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='releve_notes',
            field=models.FileField(blank=True, null=True, upload_to='preinscriptions/releves/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='serie_bac',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='annee_univ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='parametres.year'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='cni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='scolarite.filiere'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
