# Generated by Django 6.0.3 on 2026-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_remove_preinscription_bac_annee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionpedagogique',
            name='est_dette',
            field=models.BooleanField(default=False, help_text='True si cette inscription pédagogique correspond à une mise en dette globale du semestre.'),
        ),
    ]
