# Generated by Django 6.0.3 on 2026-04-24 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_etudiant_user_alter_etudiant_statut'),
        ('evaluations', '0012_remove_lignedeliberation_verrou_l3_and_more'),
        ('inscriptions', '0005_add_em_fk_to_inscriptionelement'),
        ('parametres', '0004_institution_groupe_tutelle'),
        ('scolarite', '0006_filiere_filiere_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, help_text='Snapshot de etudiant.numero_dossier au moment de la délibération.', max_length=50)),
                ('niveau_source', models.IntegerField(help_text='Niveau au moment du PV (non modifiable).')),
                ('niveau_cible', models.IntegerField(blank=True, help_text="Niveau d'inscription N+1 — null si exclusion.", null=True)),
                ('decision', models.CharField(choices=[('progression', 'Passage au niveau supérieur'), ('redoublement', 'Redoublement (consomme le droit Art. 22/28)'), ('annee_blanche', 'Année blanche médicale (Art. 23/29 — ne consomme pas le droit)'), ('exclusion', 'Exclusion définitive du cycle')], db_index=True, max_length=20)),
                ('consomme_droit_redoublement', models.BooleanField(default=False, help_text='True UNIQUEMENT si decision=redoublement. Les années blanches ne consomment pas ce droit (Art. 23/29).')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de réinscription'), ('modifiee', "Modifiée par l'administration"), ('executee', 'Inscription N+1 créée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20)),
                ('motif_modification', models.TextField(blank=True, default='', help_text='Justification du changement de filière/niveau.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressions_cible', to='parametres.year')),
                ('annee_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressions_source', to='parametres.year')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressions', to='absence.etudiant')),
                ('filiere_cible', models.ForeignKey(blank=True, help_text="Filière d'inscription N+1 — modifiable jusqu'à exécution.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progressions_cible', to='scolarite.filiere')),
                ('filiere_source', models.ForeignKey(help_text='Filière au moment du PV (non modifiable).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scolarite.filiere')),
                ('inscription_admin_creee', models.OneToOneField(blank=True, help_text='InscriptionAdministrative N+1 créée par ReinscriptionService.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_source', to='inscriptions.inscriptionadministrative')),
                ('ligne_deliberation', models.OneToOneField(blank=True, help_text='Ligne PV source (null si création administrative hors PV).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression', to='evaluations.lignedeliberation')),
                ('modifiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressions_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inscriptions_progression',
                'indexes': [models.Index(fields=['statut', 'annee_cible'], name='inscription_statut_6ea434_idx'), models.Index(fields=['decision', 'annee_cible'], name='inscription_decisio_b7db5a_idx')],
                'unique_together': {('etudiant', 'annee_cible')},
            },
        ),
    ]
