# Generated by Django 6.0.3 on 2026-04-24 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_etudiant_user_alter_etudiant_statut'),
        ('inscriptions', '0006_progression'),
        ('parametres', '0004_institution_groupe_tutelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Derogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_derogation', models.CharField(choices=[('annee_blanche', 'Année blanche (Art. 23 / Art. 29)'), ('admission_fc', 'Admission en formation continue (Art. 4)'), ('autre', 'Autre dérogation (préciser le motif)')], db_index=True, max_length=20)),
                ('motif', models.TextField(help_text='Justification administrative de la dérogation.')),
                ('justificatif', models.FileField(blank=True, help_text='Document justificatif (PDF, image) — obligatoire pour année blanche.', null=True, upload_to='derogations/%Y/')),
                ('date_decision', models.DateField(help_text='Date de la décision administrative.')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé')], db_index=True, default='actif', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derogations_admin', to='parametres.year')),
                ('decide_par', models.ForeignKey(help_text="Responsable ayant validé la dérogation (chef d'établissement).", on_delete=django.db.models.deletion.PROTECT, related_name='derogations_decidees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derogations_admin', to='absence.etudiant')),
            ],
            options={
                'db_table': 'inscriptions_derogation',
                'ordering': ['-date_decision'],
                'indexes': [models.Index(fields=['type_derogation', 'statut'], name='inscription_type_de_717e13_idx'), models.Index(fields=['annee_univ', 'statut'], name='inscription_annee_u_7a203f_idx')],
                'unique_together': {('etudiant', 'annee_univ', 'type_derogation')},
            },
        ),
    ]
