# Generated by Django 6.0.3 on 2026-04-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_add_derogation_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derogation',
            name='type_derogation',
            field=models.CharField(choices=[('annee_blanche', 'Année blanche (Art. 23 / Art. 29)'), ('derogation_inscription', "Dérogation d'inscription (au-delà du droit de redoublement)"), ('autre', 'Autre dérogation (préciser le motif)')], db_index=True, max_length=30),
        ),
    ]
