# Generated by Django 6.0.3 on 2026-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_remove_admission_fc_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derogation',
            name='type_derogation',
            field=models.CharField(choices=[('annee_blanche', 'Année blanche'), ('derogation_inscription', "Dérogation d'inscription"), ('autre', 'Autre dérogation')], db_index=True, max_length=30),
        ),
    ]
