# Generated by Django 4.2.16 on 2026-05-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0011_add_institution_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progression',
            name='decision',
            field=models.CharField(choices=[('progression', 'Passage au niveau supérieur'), ('redoublement', 'Redoublement (consomme le droit Art. 22/28)'), ('annee_blanche', 'Année blanche médicale (Art. 23/29 — ne consomme pas le droit)'), ('exclusion', 'Exclusion définitive du cycle'), ('diplomation', 'Diplômé — fin de cycle (180 crédits)')], db_index=True, max_length=20),
        ),
    ]
