# Generated by Django 4.2.16 on 2026-06-10 11:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0012_alter_progression_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='preinscriptions/photos/', validators=[core.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='preinscriptions/identite/', validators=[core.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='releve_notes',
            field=models.FileField(blank=True, null=True, upload_to='preinscriptions/releves/', validators=[core.validators.validate_document]),
        ),
    ]
