# Generated by Django 4.2.16 on 2026-06-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0012_alter_em_semestre'),
        ('inscriptions', '0013_alter_preinscription_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionelement',
            name='em',
            field=models.ForeignKey(blank=True, help_text='Élément de module (planification) lié à cette inscription. PROTECT : un EM avec des inscriptions ne peut pas être supprimé (sinon la reconstruction des dettes, clé sur em, est cassée).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_elements', to='em.em'),
        ),
    ]
