# Generated by Django 4.2.16 on 2026-06-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0014_alter_inscriptionelement_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progression',
            name='decision',
            field=models.CharField(choices=[('progression', 'Passage au niveau supérieur'), ('redoublement', 'Redoublement'), ('annee_blanche', 'Année blanche médicale (Art. 23/29 — ne consomme pas le droit)'), ('exclusion', 'Exclusion définitive du cycle'), ('diplomation', 'Diplômé — fin de cycle (180 crédits)')], db_index=True, max_length=20),
        ),
    ]
