# Generated by Django 4.2.16 on 2026-07-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0015_institution_diplome_sequence_debut'),
        ('inscriptions', '0015_alter_progression_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_diplome', models.CharField(choices=[('LP', 'Licence'), ('M', 'Master'), ('ING', 'Ingénieur'), ('Doctorat', 'Doctorat')], default='LP', max_length=20)),
                ('niveau', models.IntegerField(help_text="Année d'étude : 1, 2, 3, ...")),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grilles_frais', to='parametres.year')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_frais', to='parametres.institution')),
            ],
            options={
                'db_table': 'inscriptions_grille_frais',
                'ordering': ['annee_univ', 'type_diplome', 'niveau'],
                'indexes': [models.Index(fields=['institution', 'annee_univ', 'type_diplome', 'niveau'], name='inscription_institu_544ce1_idx')],
                'unique_together': {('institution', 'annee_univ', 'type_diplome', 'niveau')},
            },
        ),
    ]
