# Generated by Django 4.2.16 on 2026-07-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_alter_etudiant_departement'),
        ('parametres', '0015_institution_diplome_sequence_debut'),
        ('inscriptions', '0016_grillefrais'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nni', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('num_bac', models.CharField(db_index=True, max_length=20)),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200)),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=200)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1)),
                ('serie', models.CharField(blank=True, default='', max_length=50)),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, default='', max_length=50)),
                ('wilaya', models.CharField(blank=True, default='', max_length=100)),
                ('inscrit', models.BooleanField(default=False)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats_bac', to='parametres.year')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat_bac', to='absence.etudiant')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats_bac', to='parametres.institution')),
            ],
            options={
                'db_table': 'inscriptions_candidat_bac',
                'ordering': ['nom_fr', 'num_bac'],
                'indexes': [models.Index(fields=['annee_univ', 'inscrit'], name='inscription_annee_u_54e735_idx'), models.Index(fields=['nni'], name='inscription_nni_928e06_idx'), models.Index(fields=['num_bac'], name='inscription_num_bac_80eaaa_idx')],
                'unique_together': {('annee_univ', 'num_bac')},
            },
        ),
    ]
