# Generated by Django 4.2.16 on 2026-04-11 18:35

import apps.authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.authentication.models.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité')], default='AA', max_length=20),
        ),
        migrations.AlterField(
            model_name='roledefault',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserContexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(blank=True, default='', max_length=9)),
                ('semestre', models.CharField(choices=[('Pairs', 'Pairs'), ('Impairs', 'Impairs')], default='Pairs', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_usercontexte',
            },
        ),
    ]
