# Generated by Django 4.2.16 on 2026-04-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
        ('authentication', '0002_alter_customuser_avatar_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='filiere',
            field=models.ForeignKey(blank=True, help_text='Périmètre filière pour responsable_filiere / jury_president.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permissions', to='scolarite.filiere'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité'), ('responsable_filiere', 'Responsable de filière'), ('jury_president', 'Président de jury')], default='AA', max_length=20),
        ),
        migrations.AlterField(
            model_name='roledefault',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité'), ('responsable_filiere', 'Responsable de filière'), ('jury_president', 'Président de jury')], max_length=20),
        ),
    ]
