# Generated by Django 6.0.3 on 2026-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_scolarite_rbac_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité'), ('responsable_filiere', 'Responsable de filière'), ('jury_president', 'Président de jury'), ('etudiant', 'Étudiant')], default='AA', max_length=20),
        ),
        migrations.AlterField(
            model_name='roledefault',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité'), ('responsable_filiere', 'Responsable de filière'), ('jury_president', 'Président de jury'), ('etudiant', 'Étudiant')], max_length=20),
        ),
    ]
