# Generated by Django 6.0.3 on 2026-04-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_doit_changer_mdp_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité'), ('responsable_filiere', 'Responsable de filière'), ('jury_president', 'Président de jury'), ('etudiant', 'Étudiant'), ('enseignant', 'Enseignant')], default='AA', max_length=20),
        ),
        migrations.AlterField(
            model_name='roledefault',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('DG', 'Directeur général'), ('DA', 'Direction administrative'), ('DE', 'Direction enseignement'), ('AA', 'Assistant administratif'), ('IT', 'Informatique'), ('scolarite', 'Scolarité'), ('responsable_filiere', 'Responsable de filière'), ('jury_president', 'Président de jury'), ('etudiant', 'Étudiant'), ('enseignant', 'Enseignant')], max_length=20),
        ),
    ]
