# Generated by Django 4.2.16 on 2026-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0006_alter_departement_decalage_impair_and_more'),
        ('authentication', '0010_remap_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_departements',
            field=models.ManyToManyField(blank=True, db_table='authentication_user_managed_departements', help_text='Groupes que ce user peut gerer (EDT/suivi/vacation). Vide = aucune delegation.', related_name='edt_managers', to='departement.departement'),
        ),
    ]
