# Generated by Django 4.2.16 on 2026-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_add_grille_frais_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifiantPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('origine', models.CharField(choices=[('premier_acces', 'Premier accès'), ('changement', 'Changement de mot de passe')], max_length=20)),
                ('modifie_le', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portail_identifiant',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='mdp_fixe_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
