# Generated by Django 4.2.16 on 2026-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('lue_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_lecture',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlecture',
            constraint=models.UniqueConstraint(fields=('notification_id', 'user_id'), name='notifications_lecture_unique'),
        ),
    ]
