# Generated by Django 4.2.16 on 2026-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_appareils_push'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'lue'], name='notif_dest_lue_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pushenvoye',
            index=models.Index(fields=['notification_le'], name='push_envoye_le_idx'),
        ),
    ]
