# Generated by Django 4.2.16 on 2026-10-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_appareil_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur'), ('preinscription', 'Pré-inscription'), ('inscription', 'Inscription'), ('evaluation', 'Évaluation'), ('document', 'Document'), ('stage', 'Stage'), ('annonce', 'Annonce')], default='info', max_length=20),
        ),
    ]
